export const endpoint = {
  user_list: "/user/list",
  warehouse: "/warehouse",
  so_schedule: "/stock-opname",
  freeze_data: "/stock-opname/freeze/:scheduleID",
  available_freeze_data: "/stock-opname/freeze/:scheduleID/pull/list",
  pull_freeze_data: "/stock-opname/freeze/:scheduleID/pull",
  scan_item: "/stock-opname/scan/:scheduleID",
  scan_item_detail: "/stock-opname/scan/:scheduleID/:scanId",
  download_scanned_item: "/download/stock-opname/scanned/:locationId",
  summary: "/stock-opname/summary/:scheduleID",
  summary_report_preview: "/stock-opname/summary/:scheduleID/report-preview",
  adjustment: "/stock-opname/summary/:scheduleID/adjustment/:itemCode",
  save_adjustment: "/stock-opname/summary/:scheduleID/adjustment",
  finalize_summary: "/stock-opname/summary/:scheduleID/finalize",
  checkFinalize_eligible: "/stock-opname/summary/:scheduleID/finalize-eligible",
  download_summary_count: "/download/stock-opname/report/:scheduleId/count",
  download_summary_report: "/download/stock-opname/report/:scheduleId/summary",
};
